version: '3.8'
services:
  mongodb:
    container_name: simple-todo-db
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb:/app/mongodb
volumes:
  mongodb:
    driver: local
